apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-test-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
      app: nginx
  template:
    metadata:
      labels:
        io.kompose.service: nginx
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /opt/data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-pvc