---
apiVersion: v1
kind: Service
metadata:
  name: nginx-existing-lb-ip
  labels:
    k8s-app: nginx-backend
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 104.154.109.191
  selector:
    k8s-app: nginx-backend
  ports:
  - port: 80
    name: http
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-webservice
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-webservice
    spec:
      containers:
      - name: nginx
        image: library/nginx:1.15-alpine
        ports:
        - containerPort: 80
