apiVersion: v1
kind: Pod
metadata:
 name: web-cinder
spec:
 containers:
   - name: web
     image: nginx
     ports:
       - name: web
         containerPort: 80
         hostPort: 8081
         protocol: TCP
     volumeMounts:
       - name: html-volume
         mountPath: "/usr/share/nginx/html"
 volumes:
   - name: html-volume
     cinder:
       volumeID: 1f88951c-c6aa-4ab4-97ed-3fb50433aef9
       fsType: ext4